# Nom de notre workflow
name: Deploy

# Sur un événement "push" sur la branche production
on:
  push:
    branches: [deploy]

# Création de notre job deploy
jobs:
  deploy:
    # On sélectionne un ubuntu
    runs-on: ubuntu-latest

    steps:
      # On utilise une action de Github pour récupérer le repo local
      - uses: actions/checkout@v2

      # Utilisation de notre version de node
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      # Récupération de l'ensemble des commits du repository. Par défaut, le clone ne récupére pas un historique profond. Or pour Clever Cloud, c'est indispensable
      - run: git fetch --prune --unshallow

      # Installation de clever-tools and deploy app
      - run: npm install -g clever-tools
      - run: clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
      - run: clever link ${{ secrets.CLEVER_APP_ID }} --alias ubeers-strapi
      - run: clever deploy --branch deploy
