# Nom de notre workflow
name: Deploy

# Sur un événement "push" sur la branche production
on:
  push:
    branches: [production]

# Création de notre job deploy
jobs:
  deploy-and-build:
    # On sélectionne un ubuntu
    runs-on: ubuntu-latest

    steps:
      # On utilise une action de Github pour récupérer le repo local
      - uses: actions/checkout@v2

      # Utilisation de notre version de node
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1

      # Récupération de l'ensemble des commits du repository. Par défaut, le clone ne récupére pas un historique profond. Or pour Clever Cloud, c'est indispensable
      - name: Configure Git
        run: |
          git fetch --prune --unshallow
          git config --global user.email YOUR_EMAIL
          git config --global user.name YOUR_NAME

      # Build de notre administration strapi
      - name: Build Admin Panel
        run: |
          npm install 
          NODE_ENV=production npm run build

      # Commit des fichiers de build
      - name: Commit build folder
        run: |
          git add --force ./build/
          git add --force ./.cache/
          git commit -m 'strapi admin build - Github Build'

      # Installation de clever-tools and deploy app
      - name: Instal and Deploy to Clever
        run: |
          npm install -g clever-tools
          clever login --token ${{ secrets.CLEVER_TOKEN }} --secret ${{ secrets.CLEVER_SECRET }}
          clever link ${{ secrets.CLEVER_APP_ID }} --alias ubeers-strapi
          clever deploy --branch production
